# Generated by Django 6.0.6 on 2026-09-05 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0007_alter_surveillancerequest_faction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='stored_xss_demo', max_length=64)),
                ('source_ip', models.CharField(blank=True, default='127.0.0.1', max_length=64)),
                ('method', models.CharField(blank=True, default='POST', max_length=16)),
                ('path', models.CharField(blank=True, default='/security-lab/xss-demo/', max_length=255)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload_id', models.IntegerField(blank=True, null=True)),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Event Telemetry',
                'verbose_name_plural': 'Security Event Telemetry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLabPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(help_text='Controlled payload content or token')),
                ('label', models.CharField(blank=True, default='Stored XSS Demo Vector', max_length=255)),
                ('source_ip', models.CharField(blank=True, default='127.0.0.1', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('endpoint', models.CharField(blank=True, default='/security-lab/xss-demo/', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('QUARANTINED', 'Quarantined'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Security Lab Payload',
                'verbose_name_plural': 'Security Lab Payloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Observed raw indicator value')),
                ('ioc_type', models.CharField(choices=[('IP', 'IPv4 / IPv6 Address'), ('DOMAIN', 'Domain Name'), ('URL', 'Target URL'), ('HASH', 'Cryptographic Hash'), ('USER_AGENT', 'Suspicious User-Agent'), ('PAYLOAD_PATTERN', 'Payload Signature')], max_length=32)),
                ('normalized_value', models.TextField(help_text='Standardized/normalized indicator value')),
                ('reputation', models.CharField(choices=[('DEMO_MALICIOUS', 'Demo Malicious'), ('SUSPICIOUS', 'Suspicious'), ('UNKNOWN', 'Unknown'), ('CLEAN', 'Clean')], default='UNKNOWN', max_length=64)),
                ('confidence', models.IntegerField(default=0, help_text='Confidence percentage 0-100')),
                ('enrichment', models.JSONField(blank=True, default=dict, help_text='Enrichment intelligence details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='security_monitoring.securityevent')),
            ],
            options={
                'verbose_name': 'Indicator of Compromise (IOC)',
                'verbose_name_plural': 'Indicators of Compromise (IOCs)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('attack_type', models.CharField(default='Stored XSS Simulation', max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=16)),
                ('confidence', models.IntegerField(default=85)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('CONTAINED', 'Contained'), ('CLOSED', 'Closed')], default='OPEN', max_length=32)),
                ('source_ip', models.CharField(blank=True, default='127.0.0.1', max_length=64)),
                ('payload', models.TextField(blank=True, default='')),
                ('matched_sigma_rule', models.CharField(blank=True, default='', max_length=255)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_breakdown', models.JSONField(blank=True, default=list)),
                ('sigma_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('action_result', models.TextField(blank=True, default='')),
                ('containment_verified', models.BooleanField(default=False)),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions', to='tracker.spyuser')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security_monitoring.securityevent')),
                ('payload_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='security_monitoring.securitylabpayload')),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
