# Generated by Django 6.0.6 on 2026-09-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_monitoring', '0002_security_monitoring_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitylabpayload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Security Payload', 'verbose_name_plural': 'Security Payloads'},
        ),
        migrations.AddField(
            model_name='securityevent',
            name='matched_signatures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='payload_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='query_string',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='request_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='request_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='securityincident',
            name='endpoint',
            field=models.CharField(blank=True, default='/dispatch/', max_length=255),
        ),
    ]
