# Generated by Django 6.0.6 on 2026-09-05 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_monitoring', '0003_alter_securitylabpayload_options_and_more'),
        ('tracker', '0007_alter_surveillancerequest_faction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityincident',
            name='surveillance_request',
            field=models.ForeignKey(blank=True, help_text='Associated surveillance request record containing the injection payload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='tracker.surveillancerequest'),
        ),
    ]
