# Generated by Django 6.0.6 on 2026-06-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snapshot',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='state',
        ),
        migrations.RemoveField(
            model_name='snapshot',
            name='status',
        ),
        migrations.AddField(
            model_name='snapshot',
            name='current_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='current_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='last_action_relative',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='last_action_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='online_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
