# Generated by Django 6.0.6 on 2026-06-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_spyuser_campaign_owner_surveillancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='last_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_scan_error',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
