# Generated by Django 6.0.6 on 2026-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_campaign_last_scan_at_campaign_last_scan_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillancerequest',
            name='faction_id',
            field=models.CharField(max_length=500),
        ),
    ]
